version: '3.8'

services:
  # Production service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ctm-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html/public

  # Development service
  web-dev:
    image: node:18-alpine
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ctm-network
    profiles:
      - dev

networks:
  ctm-network:
    driver: bridge 