version: '3.8'

services:
  # Frontend service
  frontend:
    build: .
    ports:
      - "8080:80"
    restart: always

networks:
  ctm-network:
    name: ctm-network-${PORT:-3001}
    driver: bridge